from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

OUT = 'CJSR_Volunteer_Appreciation_Trivia_Question_Bank.docx'

def set_font(run, name='Arial', size=11, color='000000', bold=False, italic=False):
    run.font.name = name; run.font.size = Pt(size); run.font.bold = bold; run.font.italic = italic
    run.font.color.rgb = RGBColor.from_string(color)
    rpr = run._element.get_or_add_rPr(); rfonts = rpr.rFonts
    if rfonts is None:
        rfonts = OxmlElement('w:rFonts'); rpr.append(rfonts)
    rfonts.set(qn('w:ascii'), name); rfonts.set(qn('w:hAnsi'), name)

def hyperlink(paragraph, text, url):
    part = paragraph.part; rid = part.relate_to(url, 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink', is_external=True)
    h = OxmlElement('w:hyperlink'); h.set(qn('r:id'), rid)
    r = OxmlElement('w:r'); rpr = OxmlElement('w:rPr');
    color = OxmlElement('w:color'); color.set(qn('w:val'), '1155CC'); rpr.append(color)
    u = OxmlElement('w:u'); u.set(qn('w:val'), 'single'); rpr.append(u); r.append(rpr)
    t = OxmlElement('w:t'); t.text = text; r.append(t); h.append(r); paragraph._p.append(h)

def qpara(doc, question, answer, sources):
    p = doc.add_paragraph(style='List Number')
    p.paragraph_format.space_after = Pt(4); p.paragraph_format.line_spacing = 1.15
    r = p.add_run(question); set_font(r, size=11)
    r = p.add_run('\nAnswer: '); set_font(r, size=10, bold=True)
    r = p.add_run(answer); set_font(r, size=10)
    r = p.add_run('\nSource: '); set_font(r, size=9, bold=True, color='434343')
    for i, (label, url) in enumerate(sources):
        if i: p.add_run(' | ')
        hyperlink(p, label, url)

def h(doc, text, level=1):
    p = doc.add_paragraph(style=f'Heading {level}')
    r = p.add_run(text); set_font(r, size={1:20,2:16,3:14}[level], color='434343' if level==3 else '000000')
    return p

def artist(doc, name, qs):
    h(doc, name, 2)
    for q,a,s in qs: qpara(doc,q,a,s)

E = 'https://www.earshot-online.com/charts.cfm'
groups = []

groups.append(('Current Canadian independent scene', [
('Cadence Weapon', [
('What is Cadence Weapon’s real name?','Rollie Pemberton',[('About', 'https://cadenceweapon.net/ABOUT')]),
('Which civic arts role did Rollie Pemberton hold in Edmonton?','Edmonton Poet Laureate',[('About','https://cadenceweapon.net/ABOUT')]),
('Which major Canadian prize did Cadence Weapon win for Parallel World?','Polaris Music Prize',[('About','https://cadenceweapon.net/ABOUT')]),
('What is the title of Cadence Weapon’s 2024 album?','Forager',[('Bandcamp','https://cadenceweapon.bandcamp.com/album/forager')]),
('Which Edmonton radio institution is central to Cadence Weapon’s early story?','CJSR campus radio',[('Earshot feature','https://www.earshot-online.com/features/2012/June/cadence.cfm')])]),
('Sister Ray', [('Who leads Edmonton-area band Sister Ray?','Ella Coyes',[('Official site','https://www.sisterraymusic.com/')]),('Where was Ella Coyes raised?','Sturgeon County, Alberta',[('Official site','https://www.sisterraymusic.com/')]),('Where was Believer recorded?','Brooklyn, New York',[('Official site','https://www.sisterraymusic.com/')]),('What unusual writing/recording rule shaped Believer?','One song per day with minimal revisions',[('Official site','https://www.sisterraymusic.com/')]),('What national Earshot rank did Believer reach in August 2025?','#33',[('Earshot archive',E)])]),
('Sunglaciers', [('Which Alberta city is home to Sunglaciers?','Calgary',[('Bio','https://www.sunglaciers.com/bio')]),('Who are Sunglaciers’ founding members?','Evan Resnik and Mathieu Blanchard',[('Bio','https://www.sunglaciers.com/bio')]),('What field did Mathieu Blanchard study?','Family and addiction medicine',[('Bio','https://www.sunglaciers.com/bio')]),('How did Evan Resnik travel to France before the band?','He hitchhiked there',[('Bio','https://www.sunglaciers.com/bio')]),('Who co-produced Regular Nature?','Chad VanGaalen',[('Bio','https://www.sunglaciers.com/bio')])]),
('Maria Dunn', [('What was Maria Dunn’s pre-music campus-radio job?','Campus-radio DJ',[('Bio','https://www.mariadunn.com/press/bio/')]),('What is Dunn’s debut album called?','From Where I Stand',[('Bio','https://www.mariadunn.com/press/bio/')]),('Who produced all eight of Dunn’s albums?','Shannon Johnson',[('Bio','https://www.mariadunn.com/press/bio/')]),('Which JUNO category did Dunn win in 2022?','Traditional Roots Album of the Year',[('Bio','https://www.mariadunn.com/press/bio/')]),('What workplace is profiled in Piece by Piece?','Edmonton’s Great Western Garment factory',[('Bio','https://www.mariadunn.com/press/bio/')])]),
('Sour Patch Men', [('Which Alberta city is Sour Patch Men based in?','Calgary',[('Official site','https://www.sourpatchmen.com/')]),('What does the title Bownesians reference?','The band’s in-joke about their musical universe',[('Official site','https://www.sourpatchmen.com/')]),('What structural trick appears in one Sour Patch Men song?','A song within a song',[('Official site','https://www.sourpatchmen.com/')]),('Who produced and mixed the band’s record?','Taylor Cochrane',[('Official site','https://www.sourpatchmen.com/')]),('What does 4/4 Waltzes point to?','Four-four time',[('Official site','https://www.sourpatchmen.com/')])]),
('Home Front', [('Where did Home Front form?','Edmonton',[('Bandcamp','https://arewenothomefront.bandcamp.com/album/watch-it-die')]),('Who are the core members?','Graeme MacKinnon and Clint Frazier',[('Bandcamp','https://arewenothomefront.bandcamp.com/album/watch-it-die')]),('Where was Watch It Die recorded?','House of Tobester and Blee',[('Bandcamp','https://arewenothomefront.bandcamp.com/album/watch-it-die')]),('What was Watch It Die’s December 2025 Earshot rank?','#75',[('Earshot archive',E)]),('When was Watch It Die released?','November 2025',[('Bandcamp','https://arewenothomefront.bandcamp.com/album/watch-it-die')])]),
('Mariel Buckley', [('Which city is Mariel Buckley associated with?','Calgary',[('About','https://www.marielbuckley.com/about-1')]),('What is Buckley’s debut album?','Driving In The Dark',[('About','https://www.marielbuckley.com/about-1')]),('What is her second album called?','Everywhere I Used To Be',[('About','https://www.marielbuckley.com/about-1')]),('Which decade’s alternative music influenced her?','1990s grunge and alternative rock',[('About','https://www.marielbuckley.com/about-1')]),('Who are Buckley’s songs often written for?','Underdogs',[('About','https://www.marielbuckley.com/about-1')])]),
('Sargeant X Comrade', [('Who are the two people behind Sargeant X Comrade?','Yolanda Sargeant and Evgeniy Bykovets',[('News','https://sargeantxcomrade.com/news-2/')]),('Which city is the duo based in?','Calgary',[('News','https://sargeantxcomrade.com/news-2/')]),('What is the title of their Power Vol. 1 project?','Power Vol. 1',[('News','https://sargeantxcomrade.com/news-2/')]),('What cinematic genre shapes their concept?','Kung fu cinema',[('News','https://sargeantxcomrade.com/news-2/')]),('Which song appears on Escape the Matrix Part 1?','Prevail',[('News','https://sargeantxcomrade.com/news-2/')])]),
('Al Muirhead', [('What milestone did Al Muirhead mark with Still Cookin’?','His 90th birthday',[('Official site','https://www.almuirhead.com/')]),('Where did his career begin?','Regina',[('Official site','https://www.almuirhead.com/')]),('What Edmonton music shop did he open in 1966?','Arcade Music',[('Official site','https://www.almuirhead.com/')]),('At which major event did he perform under Tommy Banks?','The 1988 Olympics',[('Official site','https://www.almuirhead.com/')]),('How many JUNO nominations are noted in his bio?','Two',[('Official site','https://www.almuirhead.com/')])]),
('Blue Moon Marquee / Northern Cree', [('How is the collaboration between Blue Moon Marquee and Northern Cree described?','Powwow meets blues',[('Biography','https://bluemoonmarquee.com/biography')]),('Who are Blue Moon Marquee’s core members?','A.W. Cardinal and Jasmine Colette',[('Biography','https://bluemoonmarquee.com/biography')]),('Which Indigenous ensemble collaborated with them?','Northern Cree',[('Biography','https://bluemoonmarquee.com/biography')]),('What Earshot rank did Get Your Feathers Ready reach in December 2025?','#154',[('Earshot archive',E)]),('What JUNO distinction is claimed in their biography?','Consecutive JUNO blues-album nominations',[('Biography','https://bluemoonmarquee.com/biography')])])
]))

groups.append(('Broader Canadian independent scene', [
('Ribbon Skirt', [('What was Ribbon Skirt’s former name?','Love Language',[('Mint','https://mintrecs.com/node/7747')]),('Who leads Ribbon Skirt?','Anishinaabe artist Tashiina Buswa',[('Mint','https://mintrecs.com/node/7747')]),('What is their debut full-length?','Bite Down',[('Bandcamp','https://ribbonskirtband.bandcamp.com/album/bite-down')]),('In which month did Bite Down top Earshot’s national chart?','July 2025',[('Earshot archive',E)])]),
('Begonia', [('What is Begonia’s real name?','Alexa Dirks',[('Official site','https://www.hellobegonia.com/home')]),('Which city is she associated with?','Winnipeg',[('Official site','https://www.hellobegonia.com/home')]),('When was Fantasy Life released?','October 24, 2025',[('Bandcamp','https://hellobegonia.bandcamp.com/album/fantasy-life')]),('Where was Fantasy Life recorded?','Los Angeles and Winnipeg',[('Bandcamp','https://hellobegonia.bandcamp.com/album/fantasy-life')])]),
('FONTINE', [('In CB radio code, what does “good buddy” mean?','Gay',[('Paquin','https://www.paquinentertainment.com/artist/fontine')]),('What is FONTINE’s 2025 album called?','Good Buddy',[('Bandcamp','https://fontine.bandcamp.com/album/good-buddy')]),('How was Good Buddy recorded?','Live to tape',[('Bandcamp','https://fontine.bandcamp.com/album/good-buddy')]),('Which EP preceded Good Buddy?','Yarrow Lover',[('Paquin','https://www.paquinentertainment.com/artist/fontine')])]),
('TOPS', [('Which city formed TOPS?','Montreal',[('Rough Trade','https://www.roughtrade.com/product/tops/bury-the-key')]),('What is TOPS’ first full-length since 2020?','Bury the Key',[('Rough Trade','https://www.roughtrade.com/product/tops/bury-the-key')]),('Which label released Bury the Key?','Ghostly International',[('Rough Trade','https://www.roughtrade.com/product/tops/bury-the-key')])]),
('Katie Tupper', [('Which Saskatchewan city is Katie Tupper from?','Saskatoon',[('Killbeat','https://www.killbeatmusic.com/katietupper/')]),('What is her debut album?','Greyhound',[('Killbeat','https://www.killbeatmusic.com/katietupper/')]),('When was Greyhound released?','January 21, 2026',[('Official site','https://katietuppermusic.com/')]),('Which two EPs preceded it?','Towards the End and Where to Find Me',[('Killbeat','https://www.killbeatmusic.com/katietupper/')])]),
('Hélène Barbier', [('Where was Hélène Barbier born?','France',[('Bonsound','https://www.bonsound.com/en/artist/helene-barbier/')]),('Where has she been based for about a decade?','Montreal',[('Bonsound','https://www.bonsound.com/en/artist/helene-barbier/')]),('What is her album Panorama?','A Montreal-based album',[('Bonsound','https://www.bonsound.com/en/artist/helene-barbier/')]),('Which two languages does she switch between?','English and French',[('Bonsound','https://www.bonsound.com/en/artist/helene-barbier/')])]),
('cootie catcher', [('Which city is cootie catcher from?','Toronto',[('Apple Music','https://music.apple.com/us/artist/cootie-catcher/1634413144')]),('What is their label debut?','Shy at First',[('Apple Music','https://music.apple.com/us/artist/cootie-catcher/1634413144')]),('What is the title of their 2026 studio album?','Something We All Got',[('Apple Music','https://music.apple.com/us/artist/cootie-catcher/1634413144')]),('Name one style in their genre mix.','Garage, lo-fi, new wave, twee or jangle pop',[('Apple Music','https://music.apple.com/us/artist/cootie-catcher/1634413144')])]),
('William Prince', [('Which First Nation is William Prince from?','Peguis First Nation',[('Apple Music','https://music.apple.com/us/artist/william-prince/1333796608')]),('Which album won a JUNO?','Earthly Days',[('Apple Music','https://music.apple.com/us/artist/william-prince/1333796608')]),('Who produced Stand in the Joy?','Dave Cobb',[('Official site','https://www.williamprincemusic.com/joyhomepage')])]),
('Earshot chart pulse', [('Which act topped the national chart in both September and October 2025?','TOPS',[('Earshot archive',E)]),('Which artist topped December 2025 and January 2026?','Begonia',[('Earshot archive',E)]),('Which act topped November 2025?','FONTINE',[('Earshot archive',E)]),('Who topped February 2026?','Hélène Barbier',[('Earshot archive',E)]),('Which band topped March and April 2026?','cootie catcher',[('Earshot archive',E)]),('Which act topped July 2025?','Ribbon Skirt',[('Earshot archive',E)])])
]))

groups.append(('1997–2002 college rock', [
('The Weakerthans',[('Where did The Weakerthans form?','Winnipeg',[('Epitaph','https://www.epitaph.com/news/article/epitaph-proudly-announces-the-signing-of-the-weakerthans')]),('Who founded the band after leaving Propagandhi?','John K. Samson',[('Epitaph','https://www.epitaph.com/news/article/epitaph-proudly-announces-the-signing-of-the-weakerthans')]),('What was their debut album?','Fallow',[('Bandcamp','https://theweakerthans.bandcamp.com/album/fallow')]),('Which 2000 album followed Fallow?','Left and Leaving',[('Bandcamp','https://theweakerthans.bandcamp.com/album/fallow')]),('Which 2002 festival did Earshot highlight?','Dawson City Music Festival',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')])]),
('The New Pornographers',[('Where did The New Pornographers form?','Vancouver',[('Apple Music','https://music.apple.com/cd/artist/the-new-pornographers/4978498')]),('What was their debut album?','Mass Romantic',[('AllMusic','https://www.allmusic.com/artist/the-new-pornographers-mn0000477787')]),('Name two early members who shaped the band’s identity.','Dan Bejar and Neko Case',[('AllMusic','https://www.allmusic.com/artist/the-new-pornographers-mn0000477787')]),('In what later year did they top an Earshot annual chart?','2005',[('Earshot archive',E)])]),
('Broken Social Scene',[('Who founded Broken Social Scene?','Kevin Drew and Brendan Canning',[('Apple Music','https://music.apple.com/us/artist/broken-social-scene/6925799')]),('In what year did they form?','1999',[('Apple Music','https://music.apple.com/us/artist/broken-social-scene/6925799')]),('What was their debut album?','Feel Good Lost',[('Bucks Music Group','https://www.bucksmusicgroup.com/artists/197-broken-social-scene')]),('Which 2002 album is a landmark?','You Forgot It in People',[('Bucks Music Group','https://www.bucksmusicgroup.com/artists/197-broken-social-scene')]),('Name two associated acts.','Stars and Metric',[('Bucks Music Group','https://www.bucksmusicgroup.com/artists/197-broken-social-scene')])]),
('Constantines',[('When did the Constantines begin writing together?','1999',[('Exclaim','https://exclaim.ca/music/article/constantines-rocks_guiding_light')]),('Which earlier bands included members?','Shoulder and Captain Co-Pilot',[('Exclaim','https://exclaim.ca/music/article/constantines-rocks_guiding_light')]),('Which label first released them?','Three Gut Records',[('Apple Music','https://music.apple.com/us/artist/the-constantines/314458556')]),('Which 2002 festival appearance is notable?','Hillside Festival',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')])]),
('Metric',[('What was Metric’s original name?','Mainstream',[('Earshot interview','https://www.earshot-online.com/features/2009/November/metric.cfm')]),('When did the band form?','1998',[('Earshot interview','https://www.earshot-online.com/features/2009/November/metric.cfm')]),('Who founded Metric?','Emily Haines and James Shaw',[('Earshot interview','https://www.earshot-online.com/features/2009/November/metric.cfm')]),('Which collective is Metric associated with?','Broken Social Scene',[('Earshot interview','https://www.earshot-online.com/features/2009/November/metric.cfm')])]),
('Stars',[('What was the original Torquil Campbell/Chris Seligman project called?','Nightsongs',[('Apple Music','https://music.apple.com/am/artist/stars/336944256')]),('When did Nightsongs appear?','2001',[('Apple Music','https://music.apple.com/am/artist/stars/336944256')]),('Which two musicians joined before the full-time lineup?','Amy Millan and Evan Cranley',[('Apple Music','https://music.apple.com/am/artist/stars/336944256')]),('Where was Nightsongs recorded?','New York City',[('Apple Music','https://music.apple.com/am/artist/stars/336944256')])]),
('The Organ',[('Where did The Organ form?','Vancouver',[('Talitres','https://www.talitres.com/en/artists/the-organ.html')]),('What was their debut album?','Grab That Gun',[('Talitres','https://www.talitres.com/en/artists/the-organ.html')]),('Which earlier sound were they compared to?','1980s new wave',[('Talitres','https://www.talitres.com/en/artists/the-organ.html')]),('Which year did they top an Earshot annual chart?','2004',[('Earshot archive',E)])]),
('Royal City',[('Which city was Royal City based in?','Toronto',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')]),('Which festival did they play in 2002?','Hillside Festival',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')]),('What is their 2004 album?','Little Heart’s Ease',[('Earshot review','https://www.earshot-online.com/reviews/DisplayReview.cfm?DiscID=18415')])]),
('Sloan',[('Where did Sloan form?','Halifax',[('Earshot feature','https://www.earshot-online.com/features/2014/October/sloan.cfm')]),('Which 1998 album followed One Chord to Another?','Navy Blues',[('Earshot feature','https://www.earshot-online.com/features/2014/October/sloan.cfm')]),('What makes Sloan’s songwriting setup unusual?','All four members write songs',[('Earshot feature','https://www.earshot-online.com/features/2014/October/sloan.cfm')])]),
('Joel Plaskett Emergency',[('Which earlier band did Joel Plaskett lead?','Thrush Hermit',[('Musician Guide','https://www.musicianguide.com/biographies/1608004672/Joel-Plaskett.html')]),('What was the Emergency’s 2001 album?','Down at the Khyber',[('Album history','https://en.wikipedia.org/wiki/Down_at_the_Khyber')]),('Which city is central to Plaskett’s story?','Halifax',[('Musician Guide','https://www.musicianguide.com/biographies/1608004672/Joel-Plaskett.html')])]),
('Hawksley Workman',[('What phrase did Earshot use for Hawksley Workman?','Avant-troubadour',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')])]),
('The Sadies',[('How did Earshot describe The Sadies?','A garage/country combo',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')]),('What was their 1998 debut?','Precious Moments',[('AllMusic','https://www.allmusic.com/artist/the-sadies-mn0000495407')]),('Which singer-songwriter did they collaborate with?','Neko Case',[('AllMusic','https://www.allmusic.com/artist/the-sadies-mn0000495407')]),('Which 2002 festival did they play?','Calgary Folk Festival',[('Earshot feature','https://www.earshot-online.com/features/2002/07-feat.html')])])
]))

groups.append(('1980s DIY punk and new wave', [
('D.O.A.', [('Which city did D.O.A. come from?','Vancouver',[('Punk Canada','https://punkcanada.wordpress.com/british-columbia-2/vancouver/d-o-a/')]),('Which album popularized the word “hardcore”?','Hardcore ’81',[('CanadianBands','https://canadianbands.com/doa/')]),('What is Joey Keithley’s punk nickname?','Joey “Shithead” Keithley',[('CanadianBands','https://canadianbands.com/doa/')])]),
('Subhumans',[('Where did Subhumans form?','Vancouver',[('Official history','https://subhumans.ca/history/')]),('Which member later joined D.O.A.?','Brian “Wimpy” Goble',[('Official history','https://subhumans.ca/history/')]),('What SST album did they release?','No Wishes, No Prayers',[('Official history','https://subhumans.ca/history/')])]),
('Nomeansno',[('Which brothers founded Nomeansno?','Rob and John Wright',[('Bio','https://www.no-means-no.de/http/no-means-no.de/biography.htm')]),('Which B.C. city did they come from?','Victoria',[('Bio','https://www.no-means-no.de/http/no-means-no.de/biography.htm')]),('What is their early LP Mama?','Mama LP',[('Bio','https://www.no-means-no.de/http/no-means-no.de/biography.htm')])]),
('SNFU',[('What does SNFU stand for?','Society’s No Fucking Use',[('History','https://en.wikipedia.org/wiki/SNFU')]),('Which Alberta city was SNFU associated with?','Edmonton',[('History','https://en.wikipedia.org/wiki/SNFU')])]),
('Dayglo Abortions',[('Which city did Dayglo Abortions form in?','Victoria',[('About','https://www.daygloabortions.com/about')]),('What lyrical mode defined their early records?','Satire and sarcasm',[('About','https://www.daygloabortions.com/about')]),('What legal trouble did they face in 1988?','Obscenity charges',[('Videos','https://www.daygloabortions.com/videos')])]),
('Spoons',[('Where did Spoons form?','Burlington, Ontario',[('Bio','https://www.spoonsmusic.com/bio')]),('Who are the two core members?','Gord Deppe and Sandy Horne',[('Bio','https://www.spoonsmusic.com/bio')]),('What is their best-known early single?','Nova Heart',[('Bio','https://www.spoonsmusic.com/bio')])]),
('The Diodes',[('Which city’s scene produced The Diodes?','Toronto',[('Apple Music','https://music.apple.com/us/artist/the-diodes/14866726')]),('What major-label distinction did they claim?','First Canadian punk band signed to a major label',[('Apple Music','https://music.apple.com/us/artist/the-diodes/14866726')]),('Which song title sounds like a morning complaint?','Tired of Waking Up Tired',[('Apple Music','https://music.apple.com/us/artist/the-diodes/14866726')])]),
('Viletones',[('What was Steven Leckie’s stage name?','Nazi Dog',[('Official bio','https://www.viletonesofficial.com/bio.html')]),('Which famous club did they play in 1977?','CBGB',[('Official bio','https://www.viletonesofficial.com/bio.html')]),('Which Canadian bands shared that CBGB bill?','Diodes and Teenage Head',[('Official bio','https://www.viletonesofficial.com/bio.html')])]),
('Martha and the Muffins',[('Which city did Martha and the Muffins form in?','Toronto',[('AllMusic','https://www.allmusic.com/artist/martha-and-the-muffins-mn0000368698')]),('What was their debut album?','Metro Music',[('AllMusic','https://www.allmusic.com/artist/martha-and-the-muffins-mn0000368698')]),('What is their signature single?','Echo Beach',[('AllMusic','https://www.allmusic.com/artist/martha-and-the-muffins-mn0000368698')])]),
('Men Without Hats',[('Which Montreal band had a 1983 hit with Safety Dance?','Men Without Hats',[('LouderSound','https://www.loudersound.com/bands-artists/men-without-hats-prog-credentials-sideways')]),('Who was the lead singer?','Ivan Doroschuk',[('LouderSound','https://www.loudersound.com/bands-artists/men-without-hats-prog-credentials-sideways')]),('Who appeared on Pop Goes the World?','Ian Anderson',[('LouderSound','https://www.loudersound.com/bands-artists/men-without-hats-prog-credentials-sideways')])]),
('Scene history',[('Which 1980 Toronto Rock Against Radiation bill included D.O.A., Viletones and Forgotten Rebels?','The Rock Against Radiation concert',[('Canadian punk history','https://en.wikipedia.org/wiki/Canadian_punk_rock')]),('Which three Canadian bands played CBGB together in 1977?','Viletones, Diodes and Teenage Head',[('Viletones bio','https://www.viletonesofficial.com/bio.html')])])
]))

groups.append(('1990–1997 Canadian alternative and punk', [
('Eric’s Trip',[('Where did Eric’s Trip form?','Moncton, New Brunswick',[('AllMusic','https://www.allmusic.com/artist/erics-trip-mn0000195866')]),('What historic Sub Pop distinction did they have?','First Canadian band signed to Sub Pop',[('Sub Pop','https://www.subpop.com/artists/erics_trip')]),('What is their best-known Sub Pop album?','Love Tara',[('Sub Pop','https://www.subpop.com/artists/erics_trip')])]),
('Lowest of the Low',[('Which city did Lowest of the Low call home?','Toronto',[('History','https://en.wikipedia.org/wiki/The_Lowest_of_the_Low')]),('What was their debut album?','Shakespeare My Butt',[('History','https://en.wikipedia.org/wiki/The_Lowest_of_the_Low')]),('What was the band’s 1991 Popular Front release?','Popular Front',[('History','https://en.wikipedia.org/wiki/The_Lowest_of_the_Low')])]),
('The Inbreds',[('Which Ontario city did The Inbreds form in?','Kingston',[('Bandcamp','https://theinbreds.bandcamp.com/')]),('What unusual lineup did they use?','Bass and drums',[('Bandcamp','https://theinbreds.bandcamp.com/')]),('Who were the two members?','Mike O’Neill and Dave Ullrich',[('Bandcamp','https://theinbreds.bandcamp.com/')])]),
('Propagandhi',[('Which Manitoba town did Propagandhi originate in?','Portage la Prairie',[('Citizen Freak','https://citizenfreak.com/artists/101491-propagandhi')]),('Which 1992 tour opening was their breakthrough?','Opening for NOFX',[('Citizen Freak','https://citizenfreak.com/artists/101491-propagandhi')]),('What combination best describes their lyrical identity?','Skate punk, political critique and uncompromising ethics',[('Citizen Freak','https://citizenfreak.com/artists/101491-propagandhi')])]),
('Sloan',[('Which city did Sloan form in?','Halifax',[('Apple Music','https://music.apple.com/us/artist/sloan/1253583')]),('Which album won the 1997 JUNO for Best Alternative Album?','One Chord to Another',[('Apple Music','https://music.apple.com/us/artist/sloan/1253583')]),('What is unusual about Sloan’s songwriting?','All four members write songs',[('Apple Music','https://music.apple.com/us/artist/sloan/1253583')])]),
('Our Lady Peace',[('Which city did Our Lady Peace form in?','Toronto',[('Official site','https://www.ourladypeace.com/about')]),('What was their 1995 breakthrough album?','Naveed',[('Official site','https://www.ourladypeace.com/about')]),('Who is the lead singer?','Raine Maida',[('Official site','https://www.ourladypeace.com/about')])]),
('The Tea Party',[('Which Ontario city did The Tea Party form in?','Windsor',[('Apple Music','https://music.apple.com/us/artist/the-tea-party/528522')]),('What was their 1991 debut?','The Tea Party',[('Apple Music','https://music.apple.com/us/artist/the-tea-party/528522')]),('What was their 1995 album blending Eastern and Western sounds?','The Edges of Twilight',[('Album history','https://edges.teaparty-online.com/story/')]),('Which famous duo did they open for in Montreal in 1995?','Robert Plant and Jimmy Page',[('Band history','https://splendorsolis.teaparty-online.com/and-so-it-goes/')])]),
('I Mother Earth',[('Who were I Mother Earth’s singer and drummer?','Jagori Tanna and Christian Tanna',[('History','https://en.wikipedia.org/wiki/I_Mother_Earth')]),('What was their 1993 debut album?','Dig',[('History','https://en.wikipedia.org/wiki/Dig_%28I_Mother_Earth_album%29')]),('Which JUNO did Dig win in 1994?','Best Hard Rock Album',[('History','https://en.wikipedia.org/wiki/Dig_%28I_Mother_Earth_album%29')])]),
('Super Friendz',[('Which city did Super Friendz form in?','Halifax',[('History','https://en.wikipedia.org/wiki/The_Super_Friendz')]),('Where did the founders meet?','King’s College',[('History','https://en.wikipedia.org/wiki/The_Super_Friendz')]),('Name one founder.','Charles Austin, Matt Murphy or Drew Yamada',[('History','https://en.wikipedia.org/wiki/The_Super_Friendz')])]),
('Treble Charger',[('Which Ontario city did Treble Charger form in?','Sault Ste. Marie',[('CanadianBands','https://canadianbands.com/treble-charger/')]),('What was their original name?','NC-17',[('CanadianBands','https://canadianbands.com/treble-charger/')]),('Who founded the band?','Greig Nori',[('CanadianBands','https://canadianbands.com/treble-charger/')])]),
('Moist',[('Which city did Moist form in?','Vancouver',[('Apple Music','https://music.apple.com/us/artist/moist/14744425')]),('What was their 1994 album?','Silver',[('Apple Music','https://music.apple.com/us/artist/moist/14744425')]),('Who is Moist’s lead singer?','David Usher',[('Apple Music','https://music.apple.com/us/artist/moist/14744425')])]),
('Headstones',[('Which Ontario city did Headstones form in?','Kingston',[('Dine Alone','https://dinealonerecords.com/artists/headstones/')]),('What was their 1993 debut?','Picture of Health',[('Dine Alone','https://dinealonerecords.com/artists/headstones/')]),('Who fronts the band?','Hugh Dillon',[('Dine Alone','https://dinealonerecords.com/artists/headstones/')]),('What was their 1997 album?','Smile and Wave',[('Dine Alone','https://dinealonerecords.com/artists/headstones/')])])
]))

doc = Document()
sec = doc.sections[0]; sec.top_margin=Inches(1); sec.bottom_margin=Inches(1); sec.left_margin=Inches(1); sec.right_margin=Inches(1)
styles = doc.styles
for sty in ['Normal','List Number']:
    s=styles[sty]; s.font.name='Arial'; s.font.size=Pt(11); s._element.rPr.rFonts.set(qn('w:ascii'),'Arial'); s._element.rPr.rFonts.set(qn('w:hAnsi'),'Arial')
    s.paragraph_format.space_after=Pt(4); s.paragraph_format.line_spacing=1.15
for sty, size, before, after in [('Heading 1',20,20,6),('Heading 2',16,18,6),('Heading 3',14,16,4)]:
    s=styles[sty]; s.font.name='Arial'; s.font.size=Pt(size); s.font.bold=False; s.font.color.rgb=RGBColor.from_string('434343' if sty=='Heading 3' else '000000'); s._element.rPr.rFonts.set(qn('w:ascii'),'Arial'); s._element.rPr.rFonts.set(qn('w:hAnsi'),'Arial'); s.paragraph_format.space_before=Pt(before); s.paragraph_format.space_after=Pt(after)

p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(3); r=p.add_run('CJSR Volunteer Appreciation Night — Canadian Music Trivia Question Bank'); set_font(r,size=26)
p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(14); r=p.add_run('Research draft | Questions with answers and verification sources'); set_font(r,size=11,color='666666',italic=True)
h(doc,'How to use this draft',1)
for text in [
    'This is a consolidated question bank for CJSR’s volunteer appreciation night. It gathers the earlier current-scene, broader Canadian, 1997–2002 college-rock, 1980s DIY punk/new-wave, and 1990–1997 alternative/punk research into one review document.',
    'Answers are included so you can run two QA passes: first, fact-check every answer against the linked source; second, check wording, fairness, ambiguity, pronunciation, and whether a question is too niche for the room.',
    'Earshot is the source of truth for the modern chart questions. Earshot’s public archive does not provide a complete national chart history for the 1980s and early 1990s, so those historical sections use band biographies, label histories, and Canadian-music references instead.',
    'Some questions intentionally overlap. Combine, trim, or re-rank them after your QA passes.'
]:
    p=doc.add_paragraph(); r=p.add_run(text); set_font(r)

for section, artists in groups:
    h(doc,section,1)
    for name, qs in artists: artist(doc,name,qs)

h(doc,'Source index',1)
p=doc.add_paragraph(); r=p.add_run('Primary Earshot archive: '); set_font(r)
hyperlink(p,'earshot-online.com/charts.cfm',E)
p=doc.add_paragraph(); r=p.add_run('Additional source pages are linked inline beside each answer. Historical context for Earshot’s development is available through the NCRA archive: '); set_font(r)
hyperlink(p,'NCRA history', 'https://archive.ncra.ca/news/drumroll-please')

doc.save(OUT)
print(OUT)
